
VERILOG_SOURCES = $(DESIGN_ROOT)/std/std_data_sync.sv
VERILOG_SOURCES += $(DESIGN_ROOT)/uart/uart_tx.sv
VERILOG_SOURCES += $(DESIGN_ROOT)/uart/uart_rx.sv
VERILOG_SOURCES += $(DESIGN_ROOT)/uart/uart_top.sv

TOPLEVEL = uart_top
MODULE   = test_uart

include ../base_config.mk