# Use the exported variable from base_config.mk
# Ensure there are NO spaces at the end of these lines
VERILOG_SOURCES = $(DESIGN_ROOT)/std/std_rstn_sync.sv
VERILOG_SOURCES += $(DESIGN_ROOT)/fifo/fifo.sv

TOPLEVEL = fifo
MODULE   = test_fifo

include ../base_config.mk